// 20230201145625
// https://k8s.reg.kmitl.ac.th/api/curriculum/?function=get-registrar-curriculum&level_id=1
export interface ICurriculum {
    level_id: string;
    faculty_id: string;
    dept_id: string;
    curriculum_id: string;
    curriculum_name_th: string;
    curriculum_name_en: string;
}
export const curriculum = [
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '13',
        curriculum_id: '00',
        curriculum_name_th: 'ไม่แยกสาขาวิชา(ปกติ)',
        curriculum_name_en: '-',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '01',
        curriculum_id: '01',
        curriculum_name_th: 'วิศวกรรมโทรคมนาคม',
        curriculum_name_en: 'Telecommunications Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '02',
        curriculum_id: '02',
        curriculum_name_th: 'วิศวกรรมไฟฟ้า',
        curriculum_name_en: 'Electrical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '03',
        curriculum_id: '03',
        curriculum_name_th: 'วิศวกรรมอิเล็กทรอนิกส์',
        curriculum_name_en: 'Electronics Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '06',
        curriculum_id: '04',
        curriculum_name_th: 'วิศวกรรมเครื่องกล',
        curriculum_name_en: 'Mechanical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '07',
        curriculum_id: '05',
        curriculum_name_th: 'วิศวกรรมการวัดคุม',
        curriculum_name_en: 'Instrumentation Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '06',
        curriculum_name_th: 'วิศวกรรมคอมพิวเตอร์',
        curriculum_name_en: 'Computer Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '04',
        curriculum_id: '07',
        curriculum_name_th: 'วิศวกรรมระบบควบคุม',
        curriculum_name_en: 'Control Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '08',
        curriculum_id: '08',
        curriculum_name_th: 'วิศวกรรมโยธา',
        curriculum_name_en: 'Civil Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '09',
        curriculum_id: '09',
        curriculum_name_th: 'วิศวกรรมเกษตร',
        curriculum_name_en: 'Agricultural Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '10',
        curriculum_id: '10',
        curriculum_name_th: 'วิศวกรรมเคมี',
        curriculum_name_en: 'Chemical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '09',
        curriculum_id: '100',
        curriculum_name_th: 'วิศวกรรมระบบอุตสาหกรรมการเกษตร (ต่อเนื่อง)',
        curriculum_name_en: 'Agro-Industrial Systems Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '101',
        curriculum_name_th: 'วิศวกรรมคอมพิวเตอร์ (ต่อเนื่อง)',
        curriculum_name_en: 'Computer Engineering (Continuing Education)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '08',
        curriculum_id: '102',
        curriculum_name_th: 'วิศวกรรมโยธา (ต่อเนื่อง)',
        curriculum_name_en: 'Civil Engineering (Continuing)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '23',
        curriculum_id: '103',
        curriculum_name_th: 'วิศวกรรมชีวการแพทย์ (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Biomedical Engineering (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '14',
        curriculum_id: '104',
        curriculum_name_th: 'Industrial Engineering and  Digital Management Systems (International Program)',
        curriculum_name_en: 'Industrial Engineering and  Digital Management Systems (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '10',
        curriculum_id: '105',
        curriculum_name_th: 'วิศวกรรมเคมี (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Chemical Engineering (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '08',
        curriculum_id: '106',
        curriculum_name_th: 'วิศวกรรมโยธา (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Civil Engineering (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '07',
        curriculum_id: '107',
        curriculum_name_th: 'วิศวกรรมการวัดคุม (หลักสูตรเทียบโอน โครงการบัณฑิตพันธุ์ใหม่)',
        curriculum_name_en: 'Instrumentation Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '07',
        curriculum_id: '108',
        curriculum_name_th: 'วิศวกรรมอัตโนมัติ (หลักสูตรเทียบโอน โครงการบัณฑิตพันธุ์ใหม่)',
        curriculum_name_en: 'Automation Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '09',
        curriculum_id: '109',
        curriculum_name_th: 'วิศวกรรมระบบอุตสาหกรรมการเกษตร (หลักสูตรต่อเนื่อง โครงการบัณฑิตพันธุ์ใหม่)',
        curriculum_name_en: 'Agro-Industrial Systems Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '11',
        curriculum_id: '11',
        curriculum_name_th: 'วิศวกรรมอาหาร',
        curriculum_name_en: 'Food Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '08',
        curriculum_id: '110',
        curriculum_name_th: 'วิศวกรรมโยธา (หลักสูตรต่อเนื่อง โครงการบัณฑิตพันธุ์ใหม่)',
        curriculum_name_en: 'Civil Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '24',
        curriculum_id: '111',
        curriculum_name_th: 'วิศวกรรมหุ่นยนต์และปัญญาประดิษฐ์ (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Robotics and Artificial Intelligence Engineering (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '112',
        curriculum_name_th: 'วิศวกรรมสารสนเทศ(ชุมพร)',
        curriculum_name_en: 'Information Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '06',
        curriculum_id: '113',
        curriculum_name_th: 'วิศวกรรมเครื่องกล(แขนงวิศวกรรมเกษตร)',
        curriculum_name_en: 'Mechanical Engineering(Agriculture)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '115',
        curriculum_name_th: 'Software Engineering (International program)',
        curriculum_name_en: 'Software Engineering (International program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '14',
        curriculum_id: '116',
        curriculum_name_th: 'Financial Engineering (International)',
        curriculum_name_en: 'Financial Engineering (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '24',
        curriculum_id: '117',
        curriculum_name_th: 'Mechanical Engineering (International Program)',
        curriculum_name_en: 'Mechanical Engineering (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '24',
        curriculum_id: '118',
        curriculum_name_th: 'Electrical Engineering  (International Program)',
        curriculum_name_en: 'Electrical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '14',
        curriculum_id: '12',
        curriculum_name_th: 'วิศวกรรมอุตสาหการ',
        curriculum_name_en: 'Industrial Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '24',
        curriculum_id: '120',
        curriculum_name_th: 'Engineering and Technology Management  (International Program)',
        curriculum_name_en: 'Engineering and Technology Management  (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '08',
        curriculum_id: '121',
        curriculum_name_th: 'Engineering Management and Entrepreneurship (International Program)',
        curriculum_name_en: 'Engineering Management and Entrepreneurship (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '07',
        curriculum_id: '122',
        curriculum_name_th: 'วิศวกรรมการวัดคุม (ต่อเนื่อง)',
        curriculum_name_en: 'Instrumentation Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '14',
        curriculum_id: '123',
        curriculum_name_th: 'วิศวกรรมอุตสาหการและการจัดการโลจิสติกส์ (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Industrial Engineering and Logistics Management (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '124',
        curriculum_name_th: 'วิศวกรรมระบบไอโอทีและสารสนเทศ',
        curriculum_name_en: 'IoT System and Information Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '126',
        curriculum_name_th: 'วิศวกรรมระบบไอโอทีและสารสนเทศและฟิสิกส์อุตสาหกรรม (สองปริญญา)',
        curriculum_name_en: 'loT System and Information Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '127',
        curriculum_name_th: 'วิศวกรรมคอมพิวเตอร์ (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Computer Engineering (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '01',
        curriculum_id: '128',
        curriculum_name_th: 'วิศวกรรมไฟฟ้าสื่อสารและอิเล็กทรอนิกส์ (ต่อเนื่อง)',
        curriculum_name_en: 'Communications and Electronics Engineering (Continuing Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '13',
        curriculum_name_th: 'วิศวกรรมคอมพิวเตอร์(เร่งรัด)',
        curriculum_name_en: 'Computer Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '14',
        curriculum_name_th: 'วิศวกรรมสารสนเทศ',
        curriculum_name_en: 'Information Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '16',
        curriculum_name_th: 'วิศวกรรมสารสนเทศ(อส.บ.เทียบโอน)',
        curriculum_name_en: 'Information Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '14',
        curriculum_id: '17',
        curriculum_name_th: 'วิศวกรรมอุตสาหการ(เทียบโอนบ่าย)',
        curriculum_name_en: 'Industrial Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '03',
        curriculum_id: '20',
        curriculum_name_th: 'เทคโนโลยีอิเล็กทรอนิกส์(เช้า)',
        curriculum_name_en: 'Electronics',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '01',
        curriculum_id: '21',
        curriculum_name_th: 'เทคโนโลยีโทรคมนาคม(เช้า)',
        curriculum_name_en: 'Telecommunications Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '03',
        curriculum_id: '30',
        curriculum_name_th: 'วิศวกรรมชีวการแพทย์',
        curriculum_name_en: 'Biomedical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '02',
        curriculum_id: '31',
        curriculum_name_th: 'วิศวกรรมพลังงานไฟฟ้า',
        curriculum_name_en: 'Electrical Energy Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '03',
        curriculum_id: '40',
        curriculum_name_th: 'เทคโนโลยีอิเล็กทรอนิกส์(บ่าย)',
        curriculum_name_en: 'Electronics',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '01',
        curriculum_id: '41',
        curriculum_name_th: 'เทคโนโลยีโทรคมนาคม(บ่าย)',
        curriculum_name_en: 'Telecommunications Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '09',
        curriculum_id: '42',
        curriculum_name_th: 'วิศวกรรมเกษตร(เทียบโอนบ่าย)',
        curriculum_name_en: 'Agricultural Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '04',
        curriculum_id: '43',
        curriculum_name_th: 'วิศวกรรมแมคคาทรอนิกส์',
        curriculum_name_en: 'Mechatronics Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '10',
        curriculum_id: '44',
        curriculum_name_th: 'วิศวกรรมเคมี(เทียบโอน)',
        curriculum_name_en: 'Chemical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '11',
        curriculum_id: '45',
        curriculum_name_th: 'วิศวกรรมอาหาร(เทียบโอน)',
        curriculum_name_en: 'Food Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '01',
        curriculum_id: '46',
        curriculum_name_th: 'วิศวกรรมโทรคมนาคม (รับตรง)',
        curriculum_name_en: 'Telecommunications Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '02',
        curriculum_id: '47',
        curriculum_name_th: 'วิศวกรรมไฟฟ้า (รับตรง)',
        curriculum_name_en: 'Electrical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '07',
        curriculum_id: '48',
        curriculum_name_th: 'วิศวกรรมการวัดคุม (รับตรง)',
        curriculum_name_en: 'Instrumentation Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '49',
        curriculum_name_th: 'วิศวกรรมสารสนเทศ (รับตรง)',
        curriculum_name_en: 'Information Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '08',
        curriculum_id: '50',
        curriculum_name_th: 'วิศวกรรมโยธา (รับตรง)',
        curriculum_name_en: 'Civil Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '09',
        curriculum_id: '51',
        curriculum_name_th: 'วิศวกรรมเกษตร (รับตรง)',
        curriculum_name_en: 'Agricultural Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '03',
        curriculum_id: '52',
        curriculum_name_th: 'อิเล็กทรอนิกส์ (รับตรง)',
        curriculum_name_en: 'Electronics',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '04',
        curriculum_id: '53',
        curriculum_name_th: 'วิศวกรรมเมคคาทรอนิกส์ (รับตรง)',
        curriculum_name_en: 'Mechatronics Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '11',
        curriculum_id: '54',
        curriculum_name_th: 'วิศวกรรมอาหาร (รับตรง)',
        curriculum_name_en: 'Food Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '08',
        curriculum_id: '55',
        curriculum_name_th: 'วิศวกรรมโยธา(เทียบโอนบ่าย)',
        curriculum_name_en: 'Civil Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '04',
        curriculum_id: '56',
        curriculum_name_th: 'วิศวกรรมระบบควบคุม (รับตรง)',
        curriculum_name_en: 'Control Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '14',
        curriculum_id: '57',
        curriculum_name_th: 'วิศวกรรมอุตสาหการ (รับตรง)',
        curriculum_name_en: 'Industrial Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '10',
        curriculum_id: '58',
        curriculum_name_th: 'วิศวกรรมเคมี (รับตรง)',
        curriculum_name_en: 'Chemical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '07',
        curriculum_id: '60',
        curriculum_name_th: 'วิศวกรรมการวัดคุม(เทียบโอนเช้า)',
        curriculum_name_en: 'Instrumentation Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '07',
        curriculum_id: '61',
        curriculum_name_th: 'วิศวกรรมอัตโนมัติ',
        curriculum_name_en: 'Automation Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '10',
        curriculum_id: '62',
        curriculum_name_th: 'วิศวกรรมปิโตรเคมี',
        curriculum_name_en: 'Petrochemical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '06',
        curriculum_id: '63',
        curriculum_name_th: 'วิศวกรรมขนส่งทางราง',
        curriculum_name_en: 'Rail Transportation Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '64',
        curriculum_name_th: 'วิศวกรรมดนตรีและสื่อประสม',
        curriculum_name_en: 'Music Engineering and Multimedia',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '20',
        curriculum_id: '65',
        curriculum_name_th: 'วิศวกรรมการบินและนักบินพาณิชย์',
        curriculum_name_en: 'Aeronautical Engineering and Commercial Pilot',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '14',
        curriculum_id: '67',
        curriculum_name_th: 'วิศวกรรมออกแบบการผลิตและวัสดุ',
        curriculum_name_en: 'Production Design and Materials Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '22',
        curriculum_id: '70',
        curriculum_name_th: 'วิศวกรรมเครื่องกล (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Mechanical Engineering (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '07',
        curriculum_id: '73',
        curriculum_name_th: 'วิศวกรรมเมคคาทรอนิกส์และออโตเมชัน',
        curriculum_name_en: 'Mechatronics and Automation Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '09',
        curriculum_id: '74',
        curriculum_name_th: 'วิศวกรรมเกษตรอัจฉริยะ',
        curriculum_name_en: 'Agri-Intelligence Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '01',
        curriculum_id: '80',
        curriculum_name_th: 'วิศวกรรมโทรคมนาคม(เทียบโอนบ่าย)',
        curriculum_name_en: 'Telecommunications Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '02',
        curriculum_id: '81',
        curriculum_name_th: 'วิศวกรรมไฟฟ้า(เทียบโอนบ่าย)',
        curriculum_name_en: 'Electrical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '03',
        curriculum_id: '82',
        curriculum_name_th: 'อิเล็กทรอนิกส์(เทียบโอนบ่าย)',
        curriculum_name_en: 'Electronics',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '03',
        curriculum_id: '83',
        curriculum_name_th: 'อิเล็กทรอนิกส์(เทียบโอนบ่ายชุมพร)',
        curriculum_name_en: 'Electronics',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '84',
        curriculum_name_th: 'วิศวกรรมคอมพิวเตอร์(เทียบโอนบ่าย)',
        curriculum_name_en: 'Computer Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '07',
        curriculum_id: '85',
        curriculum_name_th: 'วิศวกรรมการวัดคุม(เทียบโอนบ่าย)',
        curriculum_name_en: 'Instrumentation Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '04',
        curriculum_id: '86',
        curriculum_name_th: 'วิศวกรรมระบบควบคุม(เทียบโอนบ่าย)',
        curriculum_name_en: 'Control Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '06',
        curriculum_id: '87',
        curriculum_name_th: 'วิศวกรรมเครื่องกล(เทียบโอนบ่าย)',
        curriculum_name_en: 'Mechanical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '06',
        curriculum_id: '88',
        curriculum_name_th: 'วิศวกรรมเครื่องกล(เทียบโอนบ่ายชุมพร)',
        curriculum_name_en: 'Mechanical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '05',
        curriculum_id: '89',
        curriculum_name_th: 'วิศวกรรมสารสนเทศ(เทียบโอนบ่าย)',
        curriculum_name_en: 'Information Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '09',
        curriculum_id: '90',
        curriculum_name_th: 'วิศวกรรมเกษตร(เทียบโอนบ่ายชุมพร)',
        curriculum_name_en: 'Agriculture Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '06',
        curriculum_id: '91',
        curriculum_name_th: 'วิศวกรรมเครื่องกล(ชุมพร)',
        curriculum_name_en: 'Mechanical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '03',
        curriculum_id: '92',
        curriculum_name_th: 'อิเล็กทรอนิกส์(ชุมพร)',
        curriculum_name_en: 'Electronics',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '09',
        curriculum_id: '93',
        curriculum_name_th: 'วิศวกรรมเกษตร(ชุมพร)',
        curriculum_name_en: 'Agriculture Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '03',
        curriculum_id: '94',
        curriculum_name_th: 'วิศวกรรมอิเล็กทรอนิกส์(ชุมพร)',
        curriculum_name_en: 'Electronics',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '02',
        curriculum_id: '95',
        curriculum_name_th: 'วิศวกรรมพลังงาน (ชุมพร)',
        curriculum_name_en: 'Energy Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '24',
        curriculum_id: '96',
        curriculum_name_th: 'Computer Innovation Engineering (International Program)',
        curriculum_name_en: 'Computer Innovation Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '24',
        curriculum_id: '97',
        curriculum_name_th: 'Energy Engineering (International Program)',
        curriculum_name_en: 'Energy Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '01',
        curriculum_id: '98',
        curriculum_name_th: 'วิศวกรรมโทรคมนาคมและโครงข่าย',
        curriculum_name_en: 'Telecommunications and Network Engineering',
    },
    {
        level_id: '1',
        faculty_id: '01',
        dept_id: '13',
        curriculum_id: '99',
        curriculum_name_th: 'ไม่แยกสาขาวิชา (รับตรง)',
        curriculum_name_en: '-',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '01',
        curriculum_id: '01',
        curriculum_name_th: 'สถาปัตยกรรม',
        curriculum_name_en: 'Architecture',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '02',
        curriculum_id: '02',
        curriculum_name_th: 'สถาปัตยกรรมภายใน',
        curriculum_name_en: 'Interior Architecture',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '03',
        curriculum_id: '03',
        curriculum_name_th: 'ศิลปอุตสาหกรรม',
        curriculum_name_en: 'Industrial Design',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '04',
        curriculum_id: '04',
        curriculum_name_th: 'นิเทศศิลป์',
        curriculum_name_en: 'Communication Design',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '04',
        curriculum_id: '05',
        curriculum_name_th: 'ภาพยนตร์และวิดีโอ',
        curriculum_name_en: 'Film and Video',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '04',
        curriculum_id: '06',
        curriculum_name_th: 'การถ่ายภาพ',
        curriculum_name_en: 'Photography',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '05',
        curriculum_id: '07',
        curriculum_name_th: 'จิตรกรรม',
        curriculum_name_en: 'Painting',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '05',
        curriculum_id: '08',
        curriculum_name_th: 'ประติมากรรม',
        curriculum_name_en: 'Sculpture',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '05',
        curriculum_id: '09',
        curriculum_name_th: 'ภาพพิมพ์',
        curriculum_name_en: 'Printmaking',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '05',
        curriculum_id: '10',
        curriculum_name_th: 'วิจิตรศิลป์(ไม่แบ่งสาขา)',
        curriculum_name_en: 'Printmaking',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '03',
        curriculum_id: '12',
        curriculum_name_th: 'ศิลปอุตสาหกรรม(โครงการสมทบพิเศษ)',
        curriculum_name_en: 'Industrial Design',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '04',
        curriculum_id: '13',
        curriculum_name_th: 'การถ่ายภาพ(โครงการสมทบพิเศษ)',
        curriculum_name_en: 'Photography',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '05',
        curriculum_id: '14',
        curriculum_name_th: 'วิจิตรศิลป์ (ไม่แบ่งสาขา) ภาคพิเศษ',
        curriculum_name_en: 'Fine Arts',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '04',
        curriculum_id: '15',
        curriculum_name_th: 'ภาพยนตร์และวิดีโอ(โครงการสมทบพิเศษ)',
        curriculum_name_en: 'Film and Video',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '05',
        curriculum_id: '16',
        curriculum_name_th: 'จิตรกรรม (ภาคพิเศษ)',
        curriculum_name_en: 'Painting',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '05',
        curriculum_id: '17',
        curriculum_name_th: 'ประติมากรรม (ภาคพิเศษ)',
        curriculum_name_en: 'Sculpture',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '05',
        curriculum_id: '18',
        curriculum_name_th: 'ภาพพิมพ์ (ภาคพิเศษ)',
        curriculum_name_en: 'Printmaking',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '01',
        curriculum_id: '19',
        curriculum_name_th: 'สถาปัตยกรรม(โครงการผลิตบัณฑิตภาคพิเศษ)',
        curriculum_name_en: 'Architecture',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '03',
        curriculum_id: '20',
        curriculum_name_th: 'การออกแบบสนเทศสามมิติ',
        curriculum_name_en: '3D-Based Communication Design',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '01',
        curriculum_id: '21',
        curriculum_name_th: 'สถาปัตยกรรมหลัก',
        curriculum_name_en: 'Architecture',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '04',
        curriculum_id: '22',
        curriculum_name_th: 'ภาพยนตร์และดิจิทัล มีเดีย',
        curriculum_name_en: 'Film and Digital Media',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '03',
        curriculum_id: '23',
        curriculum_name_th: 'ศิลปอุตสาหกรรม (หลักสูตร 4 ปี)',
        curriculum_name_en: 'Industrial Design',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '01',
        curriculum_id: '24',
        curriculum_name_th: 'ภูมิสถาปัตยกรรม',
        curriculum_name_en: 'Landscape Architecture',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '06',
        curriculum_id: '26',
        curriculum_name_th: 'จิตรกรรมและมีเดียอาตส์',
        curriculum_name_en: 'Painting and Media Arts',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '06',
        curriculum_id: '27',
        curriculum_name_th: 'ประติมากรรมและประติมากรรมเพื่อสังคม',
        curriculum_name_en: 'Sculpture and Sculpture for Society',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '06',
        curriculum_id: '28',
        curriculum_name_th: 'ภาพพิมพ์และอิลลัสเตชั่น',
        curriculum_name_en: 'Printmaking and Illustration',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '06',
        curriculum_id: '29',
        curriculum_name_th: 'จิตรกรรมและมีเดียอาตส์ ประติมากรรมและประติมากรรมเพื่อสังคม ภาพพิมพ์และอิลลัสเตชั่น',
        curriculum_name_en: 'Painting and Media Arts, Sculpture and Sculpture for Society, Printmaking and Illustration',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '07',
        curriculum_id: '30',
        curriculum_name_th: 'สถาปัตยกรรม (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Architecture (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '06',
        curriculum_id: '32',
        curriculum_name_th: 'ศิลปกรรม มีเดียอาร์ต และอิลลัสเตชันอาร์ต',
        curriculum_name_en: 'Fine Arts Media Art and Illustration Art',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '03',
        curriculum_id: '33',
        curriculum_name_th: 'การออกแบบสนเทศสามมิติและสื่อบูรณาการ',
        curriculum_name_en: 'Fine and Applied Arts Program in 3D-Based Communication Design and Integrated Media',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '06',
        curriculum_id: '34',
        curriculum_name_th: 'ศิลปะสร้างสรรค์และภัณฑารักษ์ศึกษา (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Fine Arts in Creative Arts and Curatorial Studies (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '02',
        dept_id: '07',
        curriculum_id: '35',
        curriculum_name_th: 'วิศวกรรมโยธา สถาปัตยกรรม  (หลักสูตรนานาชาติ) (สองปริญญา)',
        curriculum_name_en: '',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '01',
        curriculum_name_th: 'สถาปัตยกรรม',
        curriculum_name_en: 'Architecture',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '02',
        curriculum_name_th: 'สถาปัตยกรรมภายใน',
        curriculum_name_en: 'Interior Architecture',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '03',
        curriculum_name_th: 'ศิลปอุตสาหกรรม',
        curriculum_name_en: 'Industrial Design',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '11',
        curriculum_id: '04',
        curriculum_name_th: 'วิศวกรรมโทรคมนาคม',
        curriculum_name_en: 'Telecommunication Engineering',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '11',
        curriculum_id: '05',
        curriculum_name_th: 'อิเล็กทรอนิกส์และคอมพิวเตอร์',
        curriculum_name_en: 'Electronics and Computer',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '11',
        curriculum_id: '06',
        curriculum_name_th: 'เทคโนโลยีการวัดคุมทางอุตสาหกรรม',
        curriculum_name_en: 'Industrial Instrument Technology',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '21',
        curriculum_id: '07',
        curriculum_name_th: 'เทคโนโลยีการเกษตร-การผลิตพืช',
        curriculum_name_en: 'Agricultural Technology-Plant Production',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '21',
        curriculum_id: '08',
        curriculum_name_th: 'เทคโนโลยีการเกษตร-การผลิตสัตว์',
        curriculum_name_en: 'Agricultural  Technology Animal Production',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '21',
        curriculum_id: '09',
        curriculum_name_th: 'อุตสาหกรรมเกษตร',
        curriculum_name_en: 'Agricultural  Industry',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '31',
        curriculum_id: '10',
        curriculum_name_th: 'ภาษาญี่ปุ่น',
        curriculum_name_en: 'Japanese',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '31',
        curriculum_id: '11',
        curriculum_name_th: 'ภาษาอังกฤษเฉพาะกิจ',
        curriculum_name_en: 'English for Specific Purposes',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '12',
        curriculum_name_th: 'สถาปัตยกรรม(ภาคพิเศษ)',
        curriculum_name_en: 'Architecture',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '13',
        curriculum_name_th: 'สถาปัตยกรรมภายใน(ภาคพิเศษ)',
        curriculum_name_en: 'Interior Architecture',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '14',
        curriculum_name_th: 'ศิลปอุตสาหกรรม(ภาคพิเศษ)',
        curriculum_name_en: 'Industrial Design',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '11',
        curriculum_id: '15',
        curriculum_name_th: 'วิศวกรรมโทรคมนาคม(ภาคพิเศษ)',
        curriculum_name_en: 'Telecommunication Engineering',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '11',
        curriculum_id: '16',
        curriculum_name_th: 'อิเล็กทรอนิกส์และคอมพิวเตอร์(ภาคพิเศษ)',
        curriculum_name_en: 'Electronics and Computer',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '11',
        curriculum_id: '17',
        curriculum_name_th: 'เทคโนโลยีการวัดคุมทางอุตสาหกรรม(ภาคพิเศษ)',
        curriculum_name_en: 'Industrial Instrument Technology',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '',
        curriculum_id: '18',
        curriculum_name_th: 'เทคโนโลยีการเกษตร-การผลิตสัตว์(ภาคพิเศษ)',
        curriculum_name_en: 'Agricultural technology-Animal',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '21',
        curriculum_id: '19',
        curriculum_name_th: 'อุตสาหกรรมเกษตร(ภาคพิเศษ)',
        curriculum_name_en: 'Agricultural  Industry',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '11',
        curriculum_id: '20',
        curriculum_name_th: 'วิศวกรรมอิเล็กทรอนิกส์',
        curriculum_name_en: 'Electronics Engineering',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '11',
        curriculum_id: '21',
        curriculum_name_th: 'คอมพิวเตอร์',
        curriculum_name_en: 'Computer',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '22',
        curriculum_name_th: 'ครุศาสตร์สภาพแวดล้อมภายใน (หลักสูตร 5 ปี)',
        curriculum_name_en: 'Interior Environmental Education',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '23',
        curriculum_name_th: 'ครุศาสตร์การออกแบบ (หลักสูตร 5 ปี)',
        curriculum_name_en: 'Design  Education',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '11',
        curriculum_id: '24',
        curriculum_name_th: 'ครุศาสตร์วิศวกรรม (หลักสูตร 5 ปี)',
        curriculum_name_en: 'Engineering  Education',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '31',
        curriculum_id: '25',
        curriculum_name_th: 'ภาษาอังกฤษ',
        curriculum_name_en: 'English',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '26',
        curriculum_name_th: 'สถาปัตยกรรม(หลักสูตร 5 ปี)',
        curriculum_name_en: 'Architecture',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '21',
        curriculum_id: '27',
        curriculum_name_th: 'ครุศาสตร์เกษตร (หลักสูตร 5 ปี)',
        curriculum_name_en: 'Agricultural Education',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '28',
        curriculum_name_th: 'การออกแบบสภาพแวดล้อมภายใน (หลักสูตร 5 ปี)',
        curriculum_name_en: 'Interior Environmental Design',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '21',
        curriculum_id: '29',
        curriculum_name_th: 'เทคโนโลยีชีวภาพทางการเกษตร (ต่อเนื่อง)',
        curriculum_name_en: 'Agricultural Biotechnology (Continuing)',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '11',
        curriculum_id: '30',
        curriculum_name_th: 'เทคโนโลยีอิเล็กทรอนิกส์ (ต่อเนื่อง)',
        curriculum_name_en: 'Electronics Technology (Continuing)',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '11',
        curriculum_id: '31',
        curriculum_name_th: 'ครุศาสตร์วิศวกรรม (หลักสูตร 4 ปี)',
        curriculum_name_en: 'Engineering  Education',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '21',
        curriculum_id: '32',
        curriculum_name_th: 'ครุศาสตร์เกษตร (หลักสูตร 4 ปี)',
        curriculum_name_en: 'Agricultural Education',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '33',
        curriculum_name_th: 'ครุศาสตร์การออกแบบ (หลักสูตร 4 ปี)',
        curriculum_name_en: 'Design  Education',
    },
    {
        level_id: '1',
        faculty_id: '03',
        dept_id: '01',
        curriculum_id: '34',
        curriculum_name_th: 'เทคโนโลยีบัณฑิต (บูรณาการนวัตกรรมเพื่อสินค้าและบริการ)',
        curriculum_name_en: 'ฺBachelor of Technology (Integrated Innovation for Products and Services)',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '05',
        curriculum_id: '01',
        curriculum_name_th: 'เทคโนโลยีการผลิตพืช(ต่อเนื่อง)',
        curriculum_name_en: 'Plant Production Technology',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '07',
        curriculum_id: '02',
        curriculum_name_th: 'พัฒนาการเกษตร(ต่อเนื่อง)',
        curriculum_name_en: 'Agricultural Development',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '01',
        curriculum_id: '03',
        curriculum_name_th: 'อุตสาหกรรมเกษตร(ต่อเนื่องภาคพิเศษ)',
        curriculum_name_en: 'Agricultural Industry',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '05',
        curriculum_id: '04',
        curriculum_name_th: 'เทคโนโลยีการผลิตพืช(ต่อเนื่องชุมพร)',
        curriculum_name_en: 'Plant Production Technology',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '05',
        curriculum_id: '05',
        curriculum_name_th: 'เทคโนโลยีการผลิตพืช(ไม่แยกสาขาวิชา)',
        curriculum_name_en: 'Plant Production Technology',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '05',
        curriculum_id: '06',
        curriculum_name_th: 'พืชไร่',
        curriculum_name_en: 'Agronomy',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '04',
        curriculum_id: '07',
        curriculum_name_th: 'พืชสวน',
        curriculum_name_en: 'Horticulture',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '04',
        curriculum_id: '08',
        curriculum_name_th: 'พืชสวน(ชุมพร)',
        curriculum_name_en: 'Horticulture',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '08',
        curriculum_id: '09',
        curriculum_name_th: 'ปฐพีวิทยา',
        curriculum_name_en: 'Soil Science',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '09',
        curriculum_id: '10',
        curriculum_name_th: 'เทคโนโลยีการจัดการศัตรูพืช',
        curriculum_name_en: 'Pest Management Technology',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '14',
        curriculum_id: '100',
        curriculum_name_th: 'เศรษฐศาสตร์และธุรกิจเพื่อพัฒนาการเกษตร',
        curriculum_name_en: 'Economics and Business for Agricultural Development',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '06',
        curriculum_id: '11',
        curriculum_name_th: 'สัตวศาสตร์',
        curriculum_name_en: 'Animal Science',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '06',
        curriculum_id: '12',
        curriculum_name_th: 'สัตวศาสตร์(ชุมพร)',
        curriculum_name_en: 'Animal Science',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '01',
        curriculum_id: '13',
        curriculum_name_th: 'บริหารธุรกิจเกษตร',
        curriculum_name_en: 'Agricultural Business Administration',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '01',
        curriculum_id: '14',
        curriculum_name_th: 'เทคโนโลยีการจัดการ',
        curriculum_name_en: 'Management Technology',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '01',
        curriculum_id: '15',
        curriculum_name_th: 'อุตสาหกรรมเกษตร',
        curriculum_name_en: 'Agricultural Industry',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '01',
        curriculum_id: '16',
        curriculum_name_th: 'เทคโนโลยีการจัดการ(ภาคพิเศษ)',
        curriculum_name_en: 'Management Technology',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '01',
        curriculum_id: '17',
        curriculum_name_th: 'เทคโนโลยีการหมัก',
        curriculum_name_en: 'Fermentation Technology',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '01',
        curriculum_id: '18',
        curriculum_name_th: 'วิศวกรรมแปรรูปอาหาร',
        curriculum_name_en: 'Food Process Engineering',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '07',
        curriculum_id: '19',
        curriculum_name_th: 'พัฒนาการเกษตร',
        curriculum_name_en: 'Agricultural Development',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '03',
        curriculum_id: '20',
        curriculum_name_th: 'วิทยาศาสตร์การประมง',
        curriculum_name_en: 'Fisheries Science',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '03',
        curriculum_id: '21',
        curriculum_name_th: 'วิทยาศาสตร์การประมง(ชุมพร)',
        curriculum_name_en: 'Fisheries Science',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '01',
        curriculum_id: '22',
        curriculum_name_th: 'บริหารธุรกิจเกษตร(ภาคพิเศษ)',
        curriculum_name_en: 'Agricultural Business Administration',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '06',
        curriculum_id: '24',
        curriculum_name_th: 'เทคโนโลยีการผลิตสัตว์(ต่อเนื่องชุมพร)',
        curriculum_name_en: 'Animal Science',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '05',
        curriculum_id: '27',
        curriculum_name_th: 'พืชไร่(ภาคพิเศษ)',
        curriculum_name_en: 'Agronomy',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '04',
        curriculum_id: '28',
        curriculum_name_th: 'พืชสวน(ภาคพิเศษ)',
        curriculum_name_en: 'Horticulture',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '06',
        curriculum_id: '29',
        curriculum_name_th: 'สัตวศาสตร์(ภาคพิเศษ)',
        curriculum_name_en: 'Animal Science',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '06',
        curriculum_id: '30',
        curriculum_name_th: 'เทคโนโลยีการผลิตสัตว์ และวิทยาศาสตร์เนื้อสัตว์',
        curriculum_name_en: 'Animal Production Technology and Meat Science',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '05',
        curriculum_id: '31',
        curriculum_name_th: 'เทคโนโลยีการผลิตพืช(ต่อเนื่องพืชไร่)',
        curriculum_name_en: 'Plant Production Technology',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '04',
        curriculum_id: '32',
        curriculum_name_th: 'เทคโนโลยีการผลิตพืช(ต่อเนื่องพืชสวน)',
        curriculum_name_en: 'Plant Production Technology',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '07',
        curriculum_id: '33',
        curriculum_name_th: 'นิเทศศาสตร์เกษตร(ต่อเนื่อง)',
        curriculum_name_en: 'Agricultural Communication',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '04',
        curriculum_id: '34',
        curriculum_name_th: 'การจัดการสิ่งแวดล้อมพืชสวน',
        curriculum_name_en: 'Environmental Horticulture management',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '04',
        curriculum_id: '35',
        curriculum_name_th: 'การจัดการสิ่งแวดล้อมพืชสวน (ภาคพิเศษ)',
        curriculum_name_en: 'Environmental Horticulture Management',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '09',
        curriculum_id: '37',
        curriculum_name_th: 'เทคโนโลยีการจัดการศัตรูพืช(ภาคพิเศษ)',
        curriculum_name_en: 'Pest Management Technology',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '08',
        curriculum_id: '38',
        curriculum_name_th: 'การจัดการทรัพยากรดินและสิ่งแวดล้อม',
        curriculum_name_en: 'Soil Resources and Environment Management',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '03',
        curriculum_id: '39',
        curriculum_name_th: 'วิทยาศาสตร์การประมง(ชุมพรภาคพิเศษ)',
        curriculum_name_en: 'Fisheries Science',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '',
        curriculum_id: '40',
        curriculum_name_th: 'สัตวศาสตร์(ชุมพรภาคพิเศษ)',
        curriculum_name_en: 'Animal Science',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '07',
        curriculum_id: '41',
        curriculum_name_th: 'นิเทศศาสตร์เกษตร',
        curriculum_name_en: 'Agricultural Communication',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '01',
        curriculum_id: '42',
        curriculum_name_th: 'พัฒนาการเกษตรและการจัดการทรัพยากร',
        curriculum_name_en: 'Agricultural Economics and Resource Managemeng',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '05',
        curriculum_id: '43',
        curriculum_name_th: 'เกษตรศาสตร์',
        curriculum_name_en: 'Agriculture',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '03',
        curriculum_id: '44',
        curriculum_name_th: 'เทคโนโลยีการประมง(ชุมพร)',
        curriculum_name_en: 'Fisheries Science',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '03',
        curriculum_id: '45',
        curriculum_name_th: 'วิทยาศาสตร์การประมงและทรัพยากรทางน้ำ (ชุมพร)',
        curriculum_name_en: 'Fishery Science and Aquatic Resources',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '03',
        curriculum_id: '46',
        curriculum_name_th: 'นวัตกรรมการผลิตสัตว์น้ำ และการจัดการทรัพยากรประมง',
        curriculum_name_en: 'Innovative Aquatic Animal Production and Fishery Resource Management',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '05',
        curriculum_id: '47',
        curriculum_name_th: 'การจัดการสมาร์ตฟาร์ม-วิศวกรรมเกษตรอัจฉริยะ (สองปริญญา)',
        curriculum_name_en: 'Smart Farm Management (Multidisciplinary Curriculum)',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '05',
        curriculum_id: '48',
        curriculum_name_th: 'เทคโนโลยีการผลิตพืช',
        curriculum_name_en: 'Plant Production Technology',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '05',
        curriculum_id: '49',
        curriculum_name_th: 'การออกแบบและการจัดการภูมิทัศน์เพื่อสิ่งแวดล้อม',
        curriculum_name_en: 'Landscape for Environment ',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '05',
        curriculum_id: '50',
        curriculum_name_th: 'การจัดการสมาร์ตฟาร์ม',
        curriculum_name_en: 'Smart Farm Management',
    },
    {
        level_id: '1',
        faculty_id: '04',
        dept_id: '03',
        curriculum_id: '999',
        curriculum_name_th: 'วิทยาศาสตร์การประมง(ภาคพิเศษ)',
        curriculum_name_en: 'Fisheries Science',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '07',
        curriculum_id: '01',
        curriculum_name_th: 'คณิตศาสตร์ประยุกต์',
        curriculum_name_en: 'Applied Mathematics',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '02',
        curriculum_name_th: 'เคมีอุตสาหกรรม',
        curriculum_name_en: 'Industrial Chemistry',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '03',
        curriculum_id: '03',
        curriculum_name_th: 'เทคโนโลยีชีวภาพ',
        curriculum_name_en: 'Biotechnology',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '04',
        curriculum_id: '04',
        curriculum_name_th: 'ฟิสิกส์ประยุกต์',
        curriculum_name_en: 'Applied Physics',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '05',
        curriculum_id: '05',
        curriculum_name_th: 'สถิติประยุกต์',
        curriculum_name_en: 'Applied Statistics',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '06',
        curriculum_id: '06',
        curriculum_name_th: 'วิทยาการคอมพิวเตอร์',
        curriculum_name_en: 'Computer Science',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '07',
        curriculum_name_th: 'เคมีทรัพยากรสิ่งแวดล้อม',
        curriculum_name_en: 'Environmental Resource Chemistry',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '08',
        curriculum_name_th: 'เทคโนโลยีปิโตรเคมี (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Petrochemical Technology (International Programme)',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '09',
        curriculum_name_th: 'เคมีอุตสาหกรรม - เครื่องมือวิเคราะห์',
        curriculum_name_en: 'Industrial Chemistry - Analytical Instrumentation',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '03',
        curriculum_id: '10',
        curriculum_name_th: 'จุลชีววิทยาอุตสาหกรรม',
        curriculum_name_en: 'Industrial Microbiology',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '04',
        curriculum_id: '11',
        curriculum_name_th: 'ฟิสิกส์ประยุกต์ - เครื่องมือวิทยาศาสตร์และอุตสาหกรรม',
        curriculum_name_en: 'Applied Physics-Science and Industry Instrumentation',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '12',
        curriculum_name_th: 'วิทยาศาสตร์และเทคโนโลยีพอลิเมอร์(นานาชาติ)',
        curriculum_name_en: 'Polymer Science and Technology (International Programme)',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '07',
        curriculum_id: '13',
        curriculum_name_th: 'คณิตศาสตร์ประยุกต์(ภาคพิเศษ)',
        curriculum_name_en: 'Applied Mathematics',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '14',
        curriculum_name_th: 'เคมีอุตสาหกรรม(ภาคพิเศษ)',
        curriculum_name_en: 'Industrial Chemistry',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '03',
        curriculum_id: '15',
        curriculum_name_th: 'เทคโนโลยีชีวภาพ(ภาคพิเศษ)',
        curriculum_name_en: 'Biotechnology',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '04',
        curriculum_id: '16',
        curriculum_name_th: 'ฟิสิกส์ประยุกต์(ภาคพิเศษ)',
        curriculum_name_en: 'Applied Physics',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '05',
        curriculum_id: '17',
        curriculum_name_th: 'สถิติประยุกต์(ภาคพิเศษ)',
        curriculum_name_en: 'Applied Statistics',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '01',
        curriculum_id: '18',
        curriculum_name_th: 'วิทยาการคอมพิวเตอร์(ภาคพิเศษ)',
        curriculum_name_en: 'Computer Science',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '19',
        curriculum_name_th: 'เคมีทรัพยากรสิ่งแวดล้อม(ภาคพิเศษ)',
        curriculum_name_en: 'Environmental Resource Chemistry',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '20',
        curriculum_name_th: 'เคมีอุตสาหกรรม - เครื่องมือวิเคราะห์(ภาคพิเศษ)',
        curriculum_name_en: 'Industrial Chemistry - Analytical Instrumentation',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '03',
        curriculum_id: '21',
        curriculum_name_th: 'จุลชีววิทยาอุตสาหกรรม(ภาคพิเศษ)',
        curriculum_name_en: 'Industrial Microbiology',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '04',
        curriculum_id: '22',
        curriculum_name_th: 'ฟิสิกส์ประยุกต์-เครื่องมือวิทยาศาสตร์และอุตสาหกรรม(ภาคพิเศษ)',
        curriculum_name_en: 'Applied Physics-Science and Industry Instrumentation',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '04',
        curriculum_id: '23',
        curriculum_name_th: 'ฟิสิกส์อุตสาหกรรม',
        curriculum_name_en: 'Industrial Physics',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '24',
        curriculum_name_th: 'วิทยาศาสตร์และเทคโนโลยีพอลิเมอร์(นานาชาติ)(ภาคพิเศษ)',
        curriculum_name_en: 'Polymer Science and Technology (International Programme)',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '06',
        curriculum_id: '25',
        curriculum_name_th: 'วิทยาการคอมพิวเตอร์(นานาชาติ)(ภาคพิเศษ)',
        curriculum_name_en: 'Computer Science (International Programme)',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '26',
        curriculum_name_th: 'เทคโนโลยีปิโตรเคมี(นานาชาติ)ภาคพิเศษ',
        curriculum_name_en: 'Petrochemical Technology (International Programme)',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '06',
        curriculum_id: '30',
        curriculum_name_th: 'วิทยาการคอมพิวเตอร์ (นานาชาติ)',
        curriculum_name_en: 'Computer Science (International Programme)',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '03',
        curriculum_id: '31',
        curriculum_name_th: 'เทคโนโลยีชีวภาพ (ชุมพร)',
        curriculum_name_en: 'Biotechnology',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '32',
        curriculum_name_th: 'เคมีสิ่งแวดล้อม',
        curriculum_name_en: 'Environmental Chemistry',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '03',
        curriculum_id: '33',
        curriculum_name_th: 'จุลชีววิทยาอุตสาหกรรม (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Industrial Microbiology (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '03',
        curriculum_id: '34',
        curriculum_name_th: 'จุลชีววิทยาอุตสาหกรรม (หลักสูตรนานาชาติ/สองปริญญา)',
        curriculum_name_en: 'Industrial Microbiology (International Program)(double degree)',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '06',
        curriculum_id: '35',
        curriculum_name_th: 'วิทยาการคอมพิวเตอร์ (โครงการบัณฑิตพันธุ์ใหม่)',
        curriculum_name_en: 'Computer Science',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '36',
        curriculum_name_th: 'เคมีวิศวกรรมและอุตสาหกรรม (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Industrial and Engineering Chemistry (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '38',
        curriculum_name_th: 'เทคโนโลยีสิ่งแวดล้อมและการจัดการอย่างยั่งยืน',
        curriculum_name_en: 'Environmental Technology and Sustainable Management',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '05',
        curriculum_id: '40',
        curriculum_name_th: 'สถิติประยุกต์และการวิเคราะห์ข้อมูล',
        curriculum_name_en: 'Applied Statistics and Data Analytics',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '03',
        curriculum_id: '41',
        curriculum_name_th: 'เทคโนโลยีชีวภาพอุตสาหกรรม',
        curriculum_name_en: 'Industrial Biotechnology',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '02',
        curriculum_id: '42',
        curriculum_name_th: '',
        curriculum_name_en: '',
    },
    {
        level_id: '1',
        faculty_id: '05',
        dept_id: '11',
        curriculum_id: '43',
        curriculum_name_th: 'เทคโนโลยีดิจิทัลและนวัตกรรมเชิงบูรณาการ (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Digital Technology and Integrated Innovation',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '01',
        curriculum_id: '03',
        curriculum_name_th: 'อุตสาหกรรมเกษตร(ต่อเนื่องภาคพิเศษ)',
        curriculum_name_en: 'Agricultural Industry',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '01',
        curriculum_id: '15',
        curriculum_name_th: 'อุตสาหกรรมเกษตร',
        curriculum_name_en: 'Agricultural Industry',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '01',
        curriculum_id: '16',
        curriculum_name_th: 'เทคโนโลยีการหมักในอุตสาหกรรม',
        curriculum_name_en: 'Industrial Fermentation Technology',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '01',
        curriculum_id: '17',
        curriculum_name_th: 'เทคโนโลยีการหมัก',
        curriculum_name_en: 'Fermentation Technology',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '01',
        curriculum_id: '18',
        curriculum_name_th: 'วิศวกรรมแปรรูปอาหาร',
        curriculum_name_en: 'Food Process Engineering',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '01',
        curriculum_id: '19',
        curriculum_name_th: 'วิทยาศาสตร์และเทคโนโลยีการอาหาร',
        curriculum_name_en: 'Food Science and Technology',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '01',
        curriculum_id: '23',
        curriculum_name_th: 'อุตสาหกรรมเกษตร(ภาคพิเศษ)',
        curriculum_name_en: 'Agricultural Industry',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '04',
        curriculum_id: '35',
        curriculum_name_th: 'เทคโนโลยีการหมัก(ภาคพิเศษ)',
        curriculum_name_en: 'Fementation Technology',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '01',
        curriculum_id: '36',
        curriculum_name_th: 'วิศวกรรมแปรรูปอาหาร(ภาคพิเศษ)',
        curriculum_name_en: 'Food process Engineering',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '01',
        curriculum_id: '37',
        curriculum_name_th: 'เทคโนโลยีการหมักในอุตสาหกรรมอาหาร',
        curriculum_name_en: 'Fermentation Technology in Food Industry',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '01',
        curriculum_id: '38',
        curriculum_name_th: 'วิทยาศาสตร์การประกอบอาหารและการจัดการการบริการอาหาร (นานาชาติ)',
        curriculum_name_en: 'Culinary Science and Foodservice Management (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '06',
        dept_id: '01',
        curriculum_id: '39',
        curriculum_name_th: 'วิศวกรรมแปรรูปอาหารและวิศวกรรมอุตสาหการ (สองปริญญา)',
        curriculum_name_en: '',
    },
    {
        level_id: '1',
        faculty_id: '07',
        dept_id: '01',
        curriculum_id: '01',
        curriculum_name_th: 'เทคโนโลยีสารสนเทศ',
        curriculum_name_en: 'Information Technology',
    },
    {
        level_id: '1',
        faculty_id: '07',
        dept_id: '01',
        curriculum_id: '02',
        curriculum_name_th: 'เทคโนโลยีสารสนเทศ(ภาคพิเศษ)',
        curriculum_name_en: 'Information Technology',
    },
    {
        level_id: '1',
        faculty_id: '07',
        dept_id: '01',
        curriculum_id: '03',
        curriculum_name_th: 'เทคโนโลยีสารสนเทศทางธุรกิจ (นานาชาติ)',
        curriculum_name_en: 'Business Information Technology',
    },
    {
        level_id: '1',
        faculty_id: '07',
        dept_id: '01',
        curriculum_id: '04',
        curriculum_name_th: 'วิทยาการข้อมูลและการวิเคราะห์เชิงธุรกิจ',
        curriculum_name_en: 'Data Science and Business Analytics',
    },
    {
        level_id: '1',
        faculty_id: '07',
        dept_id: '01',
        curriculum_id: '05',
        curriculum_name_th: 'เทคโนโลยีสารสนเทศทางธุรกิจ',
        curriculum_name_en: 'Business Information Technology',
    },
    {
        level_id: '1',
        faculty_id: '09',
        dept_id: '01',
        curriculum_id: '01',
        curriculum_name_th: 'วิศวกรรมซอฟต์แวร์',
        curriculum_name_en: 'Software Engineering',
    },
    {
        level_id: '1',
        faculty_id: '09',
        dept_id: '01',
        curriculum_id: '02',
        curriculum_name_th: 'การจัดการวิศวกรรมและเทคโนโลยี',
        curriculum_name_en: 'Engineering and Technology Management',
    },
    {
        level_id: '1',
        faculty_id: '10',
        dept_id: '01',
        curriculum_id: '01',
        curriculum_name_th: 'วิศวกรรมวัสดุนาโน',
        curriculum_name_en: 'Nanomaterial Engineering',
    },
    {
        level_id: '1',
        faculty_id: '10',
        dept_id: '01',
        curriculum_id: '11',
        curriculum_name_th: 'Smart Materials Technology and Robotics and AI (Dual Degree) (International Program)',
        curriculum_name_en: 'Smart Materials Technology and Robotics and AI (Dual Degree) (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '11',
        dept_id: '01',
        curriculum_id: '01',
        curriculum_name_th: 'วิศวกรรมระบบการผลิต',
        curriculum_name_en: 'Manufacturing System Engineering',
    },
    {
        level_id: '1',
        faculty_id: '11',
        dept_id: '01',
        curriculum_id: '02',
        curriculum_name_th: 'วิศวกรรมระบบการผลิต (โครงการอาชีวะพรีเมียม)',
        curriculum_name_en: 'Manufacturing System Engineering',
    },
    {
        level_id: '1',
        faculty_id: '11',
        dept_id: '01',
        curriculum_id: '3',
        curriculum_name_th: 'วิศวกรรมระบบการผลิต (ต่อเนื่อง) (โครงการอาชีวะพรีเมียม)',
        curriculum_name_en: 'Manufacturing System Engineering (Continuing Program)',
    },
    {
        level_id: '1',
        faculty_id: '12',
        dept_id: '01',
        curriculum_id: '13',
        curriculum_name_th: 'บริหารธุรกิจเกษตร',
        curriculum_name_en: 'Agricultural Business Administration',
    },
    {
        level_id: '1',
        faculty_id: '12',
        dept_id: '01',
        curriculum_id: '14',
        curriculum_name_th: 'เทคโนโลยีการจัดการ',
        curriculum_name_en: 'Management Technology',
    },
    {
        level_id: '1',
        faculty_id: '12',
        dept_id: '01',
        curriculum_id: '15',
        curriculum_name_th: 'เทคโนโลยีการจัดการ (สำหรับการรถไฟแห่งประเทศไทย)',
        curriculum_name_en: 'Management Technology',
    },
    {
        level_id: '1',
        faculty_id: '12',
        dept_id: '01',
        curriculum_id: '16',
        curriculum_name_th: 'เทคโนโลยีการจัดการ(ภาคพิเศษ)',
        curriculum_name_en: 'Management Technology',
    },
    {
        level_id: '1',
        faculty_id: '12',
        dept_id: '01',
        curriculum_id: '17',
        curriculum_name_th: 'บริหารธุรกิจ',
        curriculum_name_en: 'Business Administration',
    },
    {
        level_id: '1',
        faculty_id: '12',
        dept_id: '01',
        curriculum_id: '18',
        curriculum_name_th: 'บริหารธุรกิจ (ใช้ภาษาอังกฤษในการเรียนการสอนในบางรายวิชา)',
        curriculum_name_en: 'Business Administration',
    },
    {
        level_id: '1',
        faculty_id: '12',
        dept_id: '01',
        curriculum_id: '22',
        curriculum_name_th: 'บริหารธุรกิจเกษตร(ภาคพิเศษ)',
        curriculum_name_en: 'Agricultural Business Administration',
    },
    {
        level_id: '1',
        faculty_id: '12',
        dept_id: '01',
        curriculum_id: '23',
        curriculum_name_th: 'บริหารธุรกิจ (นานาชาติ)',
        curriculum_name_en: 'Business Administration (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '12',
        dept_id: '02',
        curriculum_id: '24',
        curriculum_name_th: 'เศรษฐศาสตร์ธุรกิจและการจัดการ',
        curriculum_name_en: 'Business and Managerial Economics',
    },
    {
        level_id: '1',
        faculty_id: '12',
        dept_id: '01',
        curriculum_id: '25',
        curriculum_name_th: 'บริหารธุรกิจ (ชุมพร)',
        curriculum_name_en: 'Business Administration',
    },
    {
        level_id: '1',
        faculty_id: '12',
        dept_id: '01',
        curriculum_id: '26',
        curriculum_name_th: 'การเป็นผู้ประกอบการระดับโลก (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Business Administration Program in Global Entrepreneurship (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '14',
        dept_id: '01',
        curriculum_id: '01',
        curriculum_name_th: 'วิศวกรรมการบินและนักบินพาณิชย์ (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Aeronautical Engineering and Commercial Pilot (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '14',
        dept_id: '02',
        curriculum_id: '02',
        curriculum_name_th: 'การจัดการโลจิสติกส์ (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Logistics Management (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '14',
        dept_id: '01',
        curriculum_id: '3',
        curriculum_name_th: 'วิศวกรรมการบินและอวกาศ (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Engineering Program Aerospace Engineering (International  Program)',
    },
    {
        level_id: '1',
        faculty_id: '15',
        dept_id: '01',
        curriculum_id: '01',
        curriculum_name_th: 'ภาษาญี่ปุ่น',
        curriculum_name_en: 'Japanese',
    },
    {
        level_id: '1',
        faculty_id: '15',
        dept_id: '01',
        curriculum_id: '02',
        curriculum_name_th: 'ภาษาอังกฤษ',
        curriculum_name_en: 'English',
    },
    {
        level_id: '1',
        faculty_id: '15',
        dept_id: '02',
        curriculum_id: '03',
        curriculum_name_th: 'นวัตกรรมการท่องเที่ยวและการบริการ',
        curriculum_name_en: 'Innovation in Tourism and Hospitality',
    },
    {
        level_id: '1',
        faculty_id: '15',
        dept_id: '01',
        curriculum_id: '04',
        curriculum_name_th: 'ภาษาจีนเพื่ออุตสาหกรรม',
        curriculum_name_en: 'Chinese for Industry',
    },
    {
        level_id: '1',
        faculty_id: '15',
        dept_id: '01',
        curriculum_id: '05',
        curriculum_name_th: 'ภาษาญี่ปุ่นธุรกิจ',
        curriculum_name_en: 'Business Japanese',
    },
    {
        level_id: '1',
        faculty_id: '16',
        dept_id: '01',
        curriculum_id: '01',
        curriculum_name_th: 'แพทยศาสตร์ (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Doctor of Medicine (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '18',
        dept_id: '01',
        curriculum_id: '100',
        curriculum_name_th: 'วิศวกรรมดนตรีและสื่อประสม',
        curriculum_name_en: 'Music Engineering and Multimedia',
    },
    {
        level_id: '1',
        faculty_id: '19',
        dept_id: '01',
        curriculum_id: '1',
        curriculum_name_th: 'ทันตแพทยศาสตรบัณฑิต (หลักสูตรนานาชาติ)',
        curriculum_name_en: 'Doctor of Dental Surgery (International Program)',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '500',
        curriculum_name_th: 'วิศวกรรมเครื่องกล ปวส. ',
        curriculum_name_en: 'Mechanical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '501',
        curriculum_name_th: 'วิศวกรรมเครื่องกล ',
        curriculum_name_en: 'Mechanical  Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '502',
        curriculum_name_th: 'วิศวกรรมเครื่องกล (แขนงวิศวกรรรมเครื่องกลเกษตรและอาหาร)',
        curriculum_name_en: 'Mechanical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '503',
        curriculum_name_th: 'วิศวกรรมอิเล็กทรอนิกส์ ปวส. ',
        curriculum_name_en: 'Electronics  Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '504',
        curriculum_name_th: 'วิศวกรรมอิเล็กทรอนิกส์ ',
        curriculum_name_en: 'Electronics  Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '505',
        curriculum_name_th: 'วิศวกรรมพลังงาน ',
        curriculum_name_en: 'Energy Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '506',
        curriculum_name_th: 'วิศวกรรมสารสนเทศ ',
        curriculum_name_en: 'Information Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '02',
        curriculum_id: '507',
        curriculum_name_th: 'วิทยาศาสตร์การประมงและทรัพยากรทางน้ำ ',
        curriculum_name_en: 'Fisheries Technology',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '02',
        curriculum_id: '508',
        curriculum_name_th: 'สัตวศาสตร์ ',
        curriculum_name_en: 'Animal Science',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '02',
        curriculum_id: '509',
        curriculum_name_th: 'เทคโนโลยีการจัดการผลิตพืช ',
        curriculum_name_en: 'Plant Production Technology',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '03',
        curriculum_id: '510',
        curriculum_name_th: 'เทคโนโลยีชีวภาพเกษตรและอาหาร ',
        curriculum_name_en: 'Biotechnology and food',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '11',
        curriculum_id: '511',
        curriculum_name_th: 'บริหารธุรกิจ ',
        curriculum_name_en: 'Business',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '11',
        curriculum_id: '512',
        curriculum_name_th: 'บริหารธุรกิจ (ปวส.)',
        curriculum_name_en: 'Business Administration',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '513',
        curriculum_name_th: 'วิศวกรรมหุ่นยนต์และอิเล็กทรอนิกส์อัจฉริยะ',
        curriculum_name_en: 'Robotics and intelligent Electronics Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '514',
        curriculum_name_th: 'วิศวกรรมพลังงานทดแทนและยั่งยืน ',
        curriculum_name_en: 'Renewable and Sustainable Energy Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '03',
        curriculum_id: '515',
        curriculum_name_th: 'บริหารธุรกิจและการเป็นผู้ประกอบการ ',
        curriculum_name_en: 'Business Administration and Entrepreneurship',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '516',
        curriculum_name_th: 'วิศวกรรมหุ่นยนต์และอิเล็กทรอนิกส์อัจฉริยะ (ปวส.) ',
        curriculum_name_en: 'Robotics and intelligent Electronics Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '03',
        curriculum_id: '517',
        curriculum_name_th: 'บริหารธุรกิจและการเป็นผู้ประกอบการ (ปวส.) ',
        curriculum_name_en: 'Business Administration and Entrepreneurship',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '518',
        curriculum_name_th: 'วิศวกรรมสารสนเทศ (ปวส.)',
        curriculum_name_en: 'Information Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '02',
        curriculum_id: '519',
        curriculum_name_th: 'พืชสวน',
        curriculum_name_en: 'Horticulture',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '03',
        curriculum_id: '520',
        curriculum_name_th: 'เทคโนโลยีชีวภาพ',
        curriculum_name_en: 'Biotechnology',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '521',
        curriculum_name_th: 'วิศวกรรมเครื่องกล(แขนงวิศวกรรมเกษตร)',
        curriculum_name_en: 'Mechanical Engineering(Agriculture)',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '522',
        curriculum_name_th: 'วิศวกรรมคอมพิวเตอร์',
        curriculum_name_en: 'Computer Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '03',
        curriculum_id: '523',
        curriculum_name_th: 'บริหารธุรกิจและการเป็นผู้ประกอบการ (ควบสองปริญญา การจัดการธุรกิจการบิน (ม.รังสิต)',
        curriculum_name_en: 'Business Administration and Entrepreneurship',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '524',
        curriculum_name_th: 'วิศวกรรมไฟฟ้า',
        curriculum_name_en: 'Electrical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '02',
        curriculum_id: '525',
        curriculum_name_th: 'สัตวศาสตร์',
        curriculum_name_en: 'Animal Science',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '03',
        curriculum_id: '526',
        curriculum_name_th: 'นวัตกรรมอาหารและการจัดการ',
        curriculum_name_en: 'Food Innovation and Management',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '03',
        curriculum_id: '527',
        curriculum_name_th: 'บริหารธุรกิจและการเป็นผู้ประกอบการ (ควบสองปริญญา การจัดการการท่องเที่ยวและการบริการ (ม.รังสิต)',
        curriculum_name_en: 'Business Administration and Entrepreneurship',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '01',
        curriculum_id: '528',
        curriculum_name_th: 'วิศวกรรมเครื่องกล',
        curriculum_name_en: 'Mechanical Engineering',
    },
    {
        level_id: '1',
        faculty_id: '20',
        dept_id: '02',
        curriculum_id: '529',
        curriculum_name_th: 'เทคโนโลยีการผลิตพืชด้วยศาสตร์พระราชา (ปวส.)',
        curriculum_name_en: 'Plant Production Technology with the  Kings  Philosophy',
    },
    {
        level_id: '1',
        faculty_id: '95',
        dept_id: '',
        curriculum_id: '720',
        curriculum_name_th: 'นักศึกษาแลกเปลี่ยน',
        curriculum_name_en: 'International Exchange Student',
    },
];
