// 20230201145357
// https://k8s.reg.kmitl.ac.th/api/department/?function=get-registrar-department

export interface IDepartment {
    faculty_id: string;
    department_id: string;
    department_name_th: string;
    department_name_en: string;
}
export const department = [
    {
        faculty_id: '01',
        department_id: '01',
        department_name_th: 'วิศวกรรมโทรคมนาคม',
        department_name_en: 'Telecommunications Engineering',
    },
    {
        faculty_id: '01',
        department_id: '02',
        department_name_th: 'วิศวกรรมไฟฟ้า',
        department_name_en: 'Electrical Engineering',
    },
    {
        faculty_id: '01',
        department_id: '03',
        department_name_th: 'อิเล็กทรอนิกส์',
        department_name_en: 'Electronics',
    },
    {
        faculty_id: '01',
        department_id: '04',
        department_name_th: 'วิศวกรรมระบบควบคุม',
        department_name_en: 'Control Engineering',
    },
    {
        faculty_id: '01',
        department_id: '05',
        department_name_th: 'วิศวกรรมคอมพิวเตอร์',
        department_name_en: 'Computer Engineering',
    },
    {
        faculty_id: '01',
        department_id: '06',
        department_name_th: 'วิศวกรรมเครื่องกล',
        department_name_en: 'Mechanical Engineering',
    },
    {
        faculty_id: '01',
        department_id: '07',
        department_name_th: 'วิศวกรรมการวัดและควบคุม',
        department_name_en: 'Instrumentation Engineering',
    },
    {
        faculty_id: '01',
        department_id: '08',
        department_name_th: 'วิศวกรรมโยธา',
        department_name_en: 'Civil Engineering',
    },
    {
        faculty_id: '01',
        department_id: '09',
        department_name_th: 'วิศวกรรมเกษตร',
        department_name_en: 'Agricultural Engineering',
    },
    {
        faculty_id: '01',
        department_id: '10',
        department_name_th: 'วิศวกรรมเคมี',
        department_name_en: 'Chemical Engineering',
    },
    {
        faculty_id: '01',
        department_id: '11',
        department_name_th: 'วิศวกรรมอาหาร',
        department_name_en: 'Food Engineering',
    },
    {
        faculty_id: '01',
        department_id: '12',
        department_name_th: 'วิศวกรรมสารสนเทศ',
        department_name_en: 'Information Engineering',
    },
    {
        faculty_id: '01',
        department_id: '13',
        department_name_th: 'ยังไม่เลือกภาควิชา',
        department_name_en: 'Not yet selected the department',
    },
    {
        faculty_id: '01',
        department_id: '14',
        department_name_th: 'วิศวกรรมอุตสาหการ',
        department_name_en: 'Industrial Engineering',
    },
    {
        faculty_id: '01',
        department_id: '15',
        department_name_th: 'วิศวกรรมอัตโนมัติ',
        department_name_en: 'Automation Engineering',
    },
    {
        faculty_id: '01',
        department_id: '16',
        department_name_th: 'วิศวกรรมป้องกันประเทศ',
        department_name_en: 'Defence Engineering',
    },
    {
        faculty_id: '01',
        department_id: '20',
        department_name_th: 'วิศวกรรมการบินและนักบินพาณิชย์',
        department_name_en: 'Aeronautical Engineering and Commercial Pilot',
    },
    {
        faculty_id: '01',
        department_id: '22',
        department_name_th: 'วิศวกรรมแมคคาทรอนิกส์',
        department_name_en: 'Mechatronics Engineering',
    },
    {
        faculty_id: '01',
        department_id: '23',
        department_name_th: 'วิศวกรรมชีวการแพทย์',
        department_name_en: 'Biomedical Engineering',
    },
    {
        faculty_id: '01',
        department_id: '24',
        department_name_th: ' สำนักงานบริหารหลักสูตรวิศวกรรมสหวิทยาการนานาชาติ',
        department_name_en: 'School of International and Interdisciplinary Engineering Programs (SIIE)',
    },
    {
        faculty_id: '01',
        department_id: '25',
        department_name_th: 'วิศวกรรมการเงิน',
        department_name_en: 'Financial Engineering',
    },
    {
        faculty_id: '01',
        department_id: '26',
        department_name_th: 'วิศวกรรมพลังงาน',
        department_name_en: 'Energy Engineering',
    },
    {
        faculty_id: '01',
        department_id: '27',
        department_name_th: 'วิศวกรรมและการเป็นผู้ประกอบการ',
        department_name_en: 'Engineering Management and Engrepreneurship',
    },
    {
        faculty_id: '01',
        department_id: '28',
        department_name_th: 'คณะวิศวกรรมศาสตร์ ไม่ประจำภาควิชา',
        department_name_en: 'คณะวิศวกรรมศาสตร์ ไม่ประจำภาควิชา',
    },
    {
        faculty_id: '02',
        department_id: '01',
        department_name_th: 'สถาปัตยกรรม',
        department_name_en: 'Architecture',
    },
    {
        faculty_id: '02',
        department_id: '02',
        department_name_th: 'สถาปัตยกรรมภายใน',
        department_name_en: 'Interior Architecture',
    },
    {
        faculty_id: '02',
        department_id: '03',
        department_name_th: 'ศิลปอุตสาหกรรม',
        department_name_en: 'Industrial Design',
    },
    {
        faculty_id: '02',
        department_id: '04',
        department_name_th: 'นิเทศศิลป์',
        department_name_en: 'Communication Arts and Design',
    },
    {
        faculty_id: '02',
        department_id: '05',
        department_name_th: 'วิจิตรศิลป์',
        department_name_en: 'Fine Arts',
    },
    {
        faculty_id: '02',
        department_id: '06',
        department_name_th: 'ศิลปกรรม',
        department_name_en: 'Fine Arts',
    },
    {
        faculty_id: '02',
        department_id: '07',
        department_name_th: 'สำนักงานบริหารหลักสูตรสถาปัตยกรรมสหวิทยาการนานาชาติ',
        department_name_en: 'Free Department',
    },
    {
        faculty_id: '02',
        department_id: '08',
        department_name_th: 'สถาปัตยกรรมอัจฉริยะและกระบวนการคิดเชิงออกแบบ',
        department_name_en: 'Architectural Intelligence and Design Thinking ',
    },
    {
        faculty_id: '03',
        department_id: '01',
        department_name_th: 'ครุศาสตร์สถาปัตยกรรม',
        department_name_en: 'Architectural Education',
    },
    {
        faculty_id: '03',
        department_id: '05',
        department_name_th: 'ครุศาสตร์อุตสาหกรรม',
        department_name_en: 'Industrial Education',
    },
    {
        faculty_id: '03',
        department_id: '11',
        department_name_th: 'ครุศาสตร์วิศวกรรม',
        department_name_en: 'Engineering Education',
    },
    {
        faculty_id: '03',
        department_id: '21',
        department_name_th: 'ครุศาสตร์เกษตร',
        department_name_en: 'Agricultural Education',
    },
    {
        faculty_id: '03',
        department_id: '31',
        department_name_th: 'ภาษาและสังคม',
        department_name_en: 'Languages and Social Science',
    },
    {
        faculty_id: '04',
        department_id: '01',
        department_name_th: 'บริหารธุรกิจเกษตร',
        department_name_en: 'Agricultural Business Administration',
    },
    {
        faculty_id: '04',
        department_id: '03',
        department_name_th: 'วิทยาศาสตร์การประมง',
        department_name_en: 'Fisheries Science',
    },
    {
        faculty_id: '04',
        department_id: '04',
        department_name_th: 'พืชสวน',
        department_name_en: 'Horticulture',
    },
    {
        faculty_id: '04',
        department_id: '05',
        department_name_th: 'เทคโนโลยีการผลิตพืช',
        department_name_en: 'Plant Production Technology',
    },
    {
        faculty_id: '04',
        department_id: '06',
        department_name_th: 'เทคโนโลยีการผลิตสัตว์',
        department_name_en: 'Animal Production Technology',
    },
    {
        faculty_id: '04',
        department_id: '07',
        department_name_th: 'เทคนิคเกษตร',
        department_name_en: 'Agricultural Technique',
    },
    {
        faculty_id: '04',
        department_id: '08',
        department_name_th: 'ปฐพีวิทยา',
        department_name_en: 'Soil Science',
    },
    {
        faculty_id: '04',
        department_id: '09',
        department_name_th: 'เทคโนโลยีการจัดการศัตรูพืช',
        department_name_en: 'Pest Management Technology',
    },
    {
        faculty_id: '04',
        department_id: '10',
        department_name_th: 'นิเทศศาสตร์เกษตร',
        department_name_en: 'Agricultural Communication',
    },
    {
        faculty_id: '04',
        department_id: '11',
        department_name_th: 'เกษตรศาสตร์',
        department_name_en: 'Agriculture',
    },
    {
        faculty_id: '04',
        department_id: '12',
        department_name_th: 'พัฒนาการเกษตรและการจัดการทรัพยากร',
        department_name_en: 'Agriculture Development and resources management',
    },
    {
        faculty_id: '04',
        department_id: '13',
        department_name_th: 'พัฒนาการเกษตร',
        department_name_en: 'Agricultural Development',
    },
    {
        faculty_id: '04',
        department_id: '14',
        department_name_th: 'นวัตกรรมการสื่อสารและพัฒนาการเกษตร',
        department_name_en: 'Agricultural Communication Innovation and Development',
    },
    {
        faculty_id: '05',
        department_id: '01',
        department_name_th: 'คณิตศาสตร์และวิทยาการคอมพิวเตอร์',
        department_name_en: 'Mathematics and Computer Science',
    },
    {
        faculty_id: '05',
        department_id: '02',
        department_name_th: 'เคมี',
        department_name_en: 'Chemistry',
    },
    {
        faculty_id: '05',
        department_id: '03',
        department_name_th: 'ชีววิทยาประยุกต์',
        department_name_en: 'Applied Biology',
    },
    {
        faculty_id: '05',
        department_id: '04',
        department_name_th: 'ฟิสิกส์ประยุกต์',
        department_name_en: 'Applied Physics',
    },
    {
        faculty_id: '05',
        department_id: '05',
        department_name_th: 'สถิติประยุกต์',
        department_name_en: 'Applied Statistics',
    },
    {
        faculty_id: '05',
        department_id: '06',
        department_name_th: 'วิทยาการคอมพิวเตอร์',
        department_name_en: 'Department of Computer Science',
    },
    {
        faculty_id: '05',
        department_id: '07',
        department_name_th: 'คณิตศาสตร์ประยุกต์',
        department_name_en: 'Applied Mathematics',
    },
    {
        faculty_id: '05',
        department_id: '08',
        department_name_th: 'เทคโนโลยีชีวภาพ',
        department_name_en: 'Biotechnology',
    },
    {
        faculty_id: '05',
        department_id: '09',
        department_name_th: 'จุลชีววิทยาอุตสาหกรรม',
        department_name_en: 'Industrial Microbiology',
    },
    {
        faculty_id: '05',
        department_id: '10',
        department_name_th: 'คณิตศาสตร์',
        department_name_en: 'Mathematics',
    },
    {
        faculty_id: '05',
        department_id: '11',
        department_name_th: 'ศูนย์วิเคราะห์ข้อมูลดิจิทัลอัจฉริยะพระจอมเกล้าลาดกระบัง',
        department_name_en: 'KMITL Digital Analytics and Intelligence Center',
    },
    {
        faculty_id: '06',
        department_id: '01',
        department_name_th: 'อุตสาหกรรมอาหาร',
        department_name_en: 'Food Industry',
    },
    {
        faculty_id: '07',
        department_id: '01',
        department_name_th: 'เทคโนโลยีสารสนเทศ',
        department_name_en: 'Information Technology',
    },
    {
        faculty_id: '09',
        department_id: '01',
        department_name_th: 'วิทยาลัยนานาชาติ',
        department_name_en: 'International College',
    },
    {
        faculty_id: '09',
        department_id: '02',
        department_name_th: 'การจัดการวิศวกรรมและเทคโนโลยี',
        department_name_en: 'Engineering and Technology Management (International Program)',
    },
    {
        faculty_id: '09',
        department_id: '04',
        department_name_th: 'วิศวกรรมซอฟต์แวร์',
        department_name_en: 'Software Engineering',
    },
    {
        faculty_id: '10',
        department_id: '01',
        department_name_th: 'นาโนวิทยาและนาโนเทคโนโลยี',
        department_name_en: 'Nanoscience and Nanotechnology',
    },
    {
        faculty_id: '11',
        department_id: '01',
        department_name_th: 'เทคโนโลยีระบบการผลิต',
        department_name_en: 'Manufacturing System Technology',
    },
    {
        faculty_id: '12',
        department_id: '01',
        department_name_th: 'บริหารธุรกิจ',
        department_name_en: 'Department of Business',
    },
    {
        faculty_id: '12',
        department_id: '02',
        department_name_th: 'การจัดการ',
        department_name_en: 'Department of Management',
    },
    {
        faculty_id: '14',
        department_id: '01',
        department_name_th: 'วิศวกรรมการบิน',
        department_name_en: 'Aeronautical Engineering',
    },
    {
        faculty_id: '14',
        department_id: '02',
        department_name_th: 'นวัตกรรมการจัดการอุตสาหกรรมการบินและการบริการ',
        department_name_en: 'Aviation Industry Innovation and Services',
    },
    {
        faculty_id: '15',
        department_id: '01',
        department_name_th: 'ภาษา',
        department_name_en: 'Languages',
    },
    {
        faculty_id: '15',
        department_id: '02',
        department_name_th: 'มนุษยศาสตร์และสังคมศาสตร์',
        department_name_en: 'Humanities and Social Studies',
    },
    {
        faculty_id: '16',
        department_id: '01',
        department_name_th: 'แพทยศาสตรนานาชาติ',
        department_name_en: 'International Medical College',
    },
    {
        faculty_id: '17',
        department_id: '01',
        department_name_th: 'วิทยาลัยวิจัยนวัตกรรมทางการศึกษา',
        department_name_en: 'College of Educational Innovation Research',
    },
    {
        faculty_id: '18',
        department_id: '01',
        department_name_th: 'วิศวกรรมดนตรีและสื่อประสม',
        department_name_en: 'Music Engineering and Multimedia',
    },
    {
        faculty_id: '19',
        department_id: '01',
        department_name_th: 'ไม่ระบุ',
        department_name_en: 'ไม่ระบุ',
    },
    {
        faculty_id: '20',
        department_id: '01',
        department_name_th: 'วิศวกรรมศาสตร์',
        department_name_en: 'Engineering',
    },
    {
        faculty_id: '20',
        department_id: '02',
        department_name_th: 'เทคโนโลยีการเกษตร',
        department_name_en: 'Agricultural Technology',
    },
    {
        faculty_id: '20',
        department_id: '03',
        department_name_th: 'พื้นฐานทั่วไป',
        department_name_en: 'General basic',
    },
    {
        faculty_id: '20',
        department_id: '11',
        department_name_th: 'บริหารธุรกิจ',
        department_name_en: 'Business Administration',
    },
    {
        faculty_id: '90',
        department_id: '90',
        department_name_th: 'ศึกษาทั่วไป',
        department_name_en: 'General Education',
    },
];
